homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://server.home'
serial:
  port: /dev/ttyACM0
  disable_led: true
advanced:
  log_level: debug
  channel: 20
  cache_state: true
  log_directory: data/log/%TIMESTAMP%
  report: true
  network_key: [11, 33, 5, 17, 9, 11, 13, 15, 21, 2, 4, 3, 8, 10, 12, 13]
# Optional: networkmap options
map_options:
  graphviz:
    # Colors to be used in the graphviz network map
    colors:
      fill:
        enddevice: '#fff8ce'
        coordinator: '#e04e5d'
        router: '#4ea3e0'
      font:
        coordinator: '#ffffff'
        router: '#ffffff'
        enddevice: '#000000'
      line:
        active: '#009900'
        inactive: '#994444'

devices: devices.yaml
